---
- name: Создать папку приложения
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ubuntu
    mode: '0755'

- name: Создать index.html из шаблона
  template:
    src: index.html.j2
    dest: "{{ app_dir }}/index.html"
    owner: ubuntu
    mode: '0644'

- name: Запустить nginx
  shell: |
    docker stop {{ app_name }} || true
    docker rm {{ app_name }} || true
    docker run -d \
      -p {{ app_port }}:80 \
      -v {{ app_dir }}:/usr/share/nginx/html \
      --name {{ app_name }} \
      --restart always \
      nginx:alpine
